# Permalinks
permalink: /blog/:year/:month/:day/:title.html

# Setup
title: '大树的博客'
tagline: ''
description: '天行健，君子以自强不息'
baseurl: 'http://0000-bigtree.github.io'
url: 'http://0000-bigtree.github.io'
github_username: '0000-bigree'

markdown: kramdown
paginate: 5
paginate_path: "blog/page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
