# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:  '大树的博客'
tagline: ''
description: '天行健，君子以自强不息'
baseurl: ""
url: "http://0000-bigtree.github.io"
github_username:  0000-bigree
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
